common:
  seed: 42

ppo:
  num_res_blocks: 10
  channels: 128
  activation: relu
  gamma: 0.99
  optimizer: adam
  clip_eps: 0.2  
  entropy_coef: 0.01
  value_coef: 0.5
  learning_rate: 0.0003
  epochs: 4
  batch_size: 64

mcts:
  sim_num: 800
  cpuct: 1.5
  dirichlet_alpha: 0.3
  temperature: 1.0
  value_coef: 0.5
  epochs: 4
  batch_size: 64
  use_variable_sim_num: False

mcts_nn:
  use_nn: true
  nn_path: ./models/policy_value.pt
