policy_value_data_collection:
  batch_size: 64
  count: 2048
  gamma: 0.99
  num_games: 10
policy_value_train:
  batch_size: 128
  epochs: 5
  learning_rate: 0.001
  optimizer: adam
  value_coef: 1.0
  weight_decay: 0.0001
ppo:
  model:
    activation: relu
    channels: 128
    num_res_blocks: 10
  train:
    batch_size: 64
    clip_eps: 0.2
    entropy_coef: 0.01
    epochs: 10
    learning_rate: 0.001
    optimizer: adam
    value_coef: 0.5
ppo_data_collection:
  count: 2048
  gamma: 0.99
